// Fonte única da categorização das keywords nos três nichos do painel. O
// scraper (scraper/keywords.ts) importa daqui pra montar a lista de busca —
// e o site importa daqui pra filtrar o catálogo por nicho — assim as duas
// pontas nunca ficam fora de sincronia. A ORDEM de cada array importa pro
// scraper (é a ordem de rotação do cursor); mudar a ordem aqui muda a ordem
// de varredura da mineração.
export type Categoria = "saude" | "religiao" | "renda_extra";

export const CATEGORIA_LABEL: Record<Categoria, string> = {
  saude: "Saúde",
  religiao: "Religião",
  renda_extra: "Renda extra",
};

export const KEYWORD_GROUPS: Record<Categoria, string[]> = {
  saude: [
    "guia de emagrecimento",
    "protocolo de emagrecimento",
    "cardápio de emagrecimento",
    "jejum intermitente",
    "receitas low carb",
    "receitas fit",
    "alimentação saudável",
    "receitas para diabéticos",
    "treino em casa",
    "treino para mulheres",
    "protocolo de treino em casa",
    "planilhas de treino",
    "guia de musculação",
    "guia da barra fixa",
    "alongamento em casa",
    "exercícios para dor nas costas",
    "yoga para iniciantes",
    "fisioterapia pélvica",
    "saúde da mulher",
    "menopausa",
    "guia do sono",
    "guia de primeiros socorros",
    "apostila de enfermagem",
    "resumos de enfermagem",
    "resumo de farmacologia",
    "controle da ansiedade",
    "meditação guiada",
    "diário de gratidão para imprimir",
    "diário de autoconhecimento",
    "arteterapia atividades",
    "terapias holísticas",
    "aromaterapia",
    "reiki",
    "florais de bach",
    "auriculoterapia",
    "cromoterapia",
    "massagem relaxante",
    "tarot guia completo",
    "curso de numerologia",
    "dieta cetogênica",
    "receitas sem glúten",
    "receitas sem lactose",
    "guia de nutrição",
    "caminhada para emagrecer",
    "barriga chapada",
    "pilates em casa",
    "hipertrofia feminina",
    "ganhar massa muscular",
    "intestino preso",
    "refluxo e gastrite",
    "colesterol alto",
    "pressão alta",
    "enxaqueca",
    "insônia",
    "dor no joelho",
    "hérnia de disco",
    "saúde do homem",
    "resumo de anatomia",
    "crise de ansiedade",
    "autoestima",
    "mindfulness",
  ],
  religiao: [
    "devocional católica",
    "catequese atividades",
    "estudo bíblico em PDF",
    "estudo bíblico para mulheres",
    "estudo de salmos",
    "plano de leitura bíblica",
    "oração diária",
    "novena",
    "abas divisórias para bíblia",
    "kit crochê católico",
    "cartão evangelismo digital",
    "escola dominical atividades",
    "atividades bíblicas infantis",
    "material de discipulado",
    "sermão pronto",
    "devocional para casais",
    "cifras gospel",
    "devocional",
    "estudo bíblico",
    "bíblia de estudo",
    "versículos para imprimir",
    "diário de oração",
    "orações católicas",
    "livro de orações",
    "santo terço",
    "material de crisma",
    "primeira eucaristia",
    "guerra espiritual",
    "esboço de sermão",
    "pregação pronta",
    "ministério infantil",
    "culto infantil",
    "escola dominical infantil",
    "mulher de fé",
    "casamento cristão",
  ],
  renda_extra: [
    "renda extra em casa",
    "trabalhar em casa",
    "vender no Mercado Livre",
    "brechó online",
    "artesanato para vender",
    "crochê para vender",
    "personalizados para vender",
    "lembrancinhas para vender",
    "kit de festa para vender",
    "vender na Shopee",
    "revenda de roupas",
    "dropshipping",
    "marketing digital",
    "afiliado iniciante",
    "adesivos para vender",
    "canecas personalizadas",
    "sublimação",
    "cuidador de idosos",
    "gráficos de crochê",
    "moldes de crochê",
    "receitas de crochê",
    "pontos de crochê",
    "amigurumi passo a passo",
    "moldes de tricô",
    "touca de crochê",
    "moldes de costura",
    "curso de corte e costura",
    "curso de costura para iniciantes",
    "moldes de roupas infantis",
    "moldes de vestidos",
    "moldes de bolsas",
    "moldes de bordado",
    "roupinhas pet moldes",
    "roupinha de cachorro",
    "moldes editáveis Canva",
    "kit festa infantil digital",
    "topo de bolo para imprimir",
    "kit lembrancinha digital",
    "kit digital de etiquetas",
    "moldes de letras",
    "moldes de números",
    "revistinha para colorir",
    "paper squishy",
    "planner para imprimir",
    "moldes de EVA",
    "scrapbook",
    "tags personalizadas",
    "mesa posta moldes",
    "moldes de feltro",
    "patchwork",
    "velas artesanais",
    "sabonetes artesanais",
    "resina epóxi",
    "biscuit passo a passo",
    "mesversário",
    "chá revelação",
    "moldes de natal",
    "kit natal digital",
    "moldes de páscoa",
    "kit páscoa digital",
    "moldes de halloween",
    "decoração junina para imprimir",
    "salgados para vender",
    "doces para vender",
    "bolo no pote",
    "marmitas para vender",
    "receitas de geladinho gourmet",
    "curso de brigadeiro gourmet",
    "curso de doces gourmet",
    "cardápio de confeitaria digital",
    "cardápio digital editável",
    "confeitaria para iniciantes",
    "pães caseiros",
    "hambúrguer artesanal",
    "manual do eletricista",
    "apostila de elétrica residencial",
    "curso de refrigeração",
    "curso de climatização",
    "projetos de marcenaria",
    "projetos de serralheria",
    "curso de adestramento online",
    "curso de jardinagem online",
    "templates para Canva Instagram",
    "pack de stories editáveis",
    "kit redes sociais digital",
    "planner de conteúdo editável",
  ],
};

const LOOKUP: Record<string, Categoria> = Object.fromEntries(
  (Object.entries(KEYWORD_GROUPS) as [Categoria, string[]][]).flatMap(([categoria, keywords]) =>
    keywords.map((k) => [k, categoria] as const)
  )
);

// Uma oferta guarda em `niche` a keyword exata que a achou. Se a keyword não
// estiver mapeada (lista mudou depois que a oferta foi minerada), volta null
// — a oferta some do filtro por nicho, mas continua aparecendo em "Todas".
export function categoriaDaNiche(niche: string): Categoria | null {
  return LOOKUP[niche] ?? null;
}
