// Lista de keywords usadas na rotação circular de mineração de ofertas novas.
// Índice inicial = dia do ano % KEYWORDS.length; cada rodada pega as 7
// seguintes (circular). Lista expandida pelo Cayan — mantidas fora dela,
// de propósito, as keywords de concurso público (apostila PRF/PMMA/
// Petrobras/ENEM etc.): regra de negócio já confirmada é não minerar nesse
// nicho (mercado grande/saturado, dominado por players grandes).
export const KEYWORDS: string[] = [
  "PDF por apenas",
  "guia completo por apenas",
  "material digital por apenas",
  "acesso vitalício por apenas",
  "moldes por apenas",
  "pronto para imprimir",
  "apostila por apenas",
  "arquivo digital por apenas",
  "kit digital por apenas",
  "aulas em vídeo por apenas",
  "e-book por apenas",
  "curso online por apenas",
  "planilha por apenas",
  "modelo editável por apenas",
  "receba em PDF",
  "gráficos de crochê",
  "moldes de costura",
  "moldes de crochê",
  "receitas de crochê",
  "pontos de crochê",
  "amigurumi passo a passo",
  "moldes de tricô",
  "curso de corte e costura",
  "moldes de roupas infantis",
  "moldes de bolsas",
  "moldes de vestidos",
  "moldes de touca",
  "moldes de chinelo",
  "moldes editáveis Canva",
  "moldes para Cricut",
  "kit festa infantil digital",
  "convites editáveis digital",
  "topo de bolo para imprimir",
  "moldes de letras",
  "moldes de números",
  "kit lembrancinha digital",
  "revistinha para colorir",
  "paper squishy",
  "kit digital de etiquetas",
  "planner para imprimir",
  "moldes de EVA",
  "moldes de scrapbook",
  "moldes de tag personalizada",
  "atividades de alfabetização",
  "consciência fonológica",
  "atividades para imprimir educação infantil",
  "caderno de caligrafia",
  "desenhos para colorir",
  "kit de atividades por apenas",
  "sequência didática pronta",
  "jogos pedagógicos para imprimir",
  "atividades de matemática infantil",
  "grafismo e alfabetização",
  "dot to dot",
  "livro personalizado por IA",
  "projetos de robótica",
  "robótica infantil kit",
  "brincadeiras sem tela",
  "feira de ciências pronta",
  "experimentos científicos para imprimir",
  "planilhas de treino",
  "guia de musculação",
  "guia da barra fixa",
  "curso de extensão de cílios",
  "curso de design de sobrancelhas",
  "spa dos pés curso",
  "curso de alongamento de unhas",
  "protocolo de treino em casa",
  "curso de maquiagem online",
  "curso de manicure online",
  "curso de micropigmentação",
  "catequese atividades",
  "devocional católica",
  "diário da mulher católica",
  "estudo bíblico em PDF",
  "abas divisórias para bíblia",
  "kit crochê católico",
  "cartão evangelismo digital",
  "escola dominical atividades",
  "roupinhas pet moldes",
  "anatomia veterinária",
  "doenças bovinas",
  "curso de adestramento online",
  "moldes de roupa para cachorro",
  "projetos de serralheria",
  "curso de refrigeração",
  "curso de ar condicionado",
  "manual do eletricista",
  "projetos de marcenaria",
  "apostila de elétrica residencial",
  "mesa posta moldes",
  "arteterapia atividades",
  "harmonização facial estudo",
  "planner financeiro editável",
  "receitas de geladinho gourmet",
  "cardápio de confeitaria digital",
  "curso de brigadeiro gourmet",
  "curso de doces gourmet",
  "guia de organização da casa",
  "curso de jardinagem online",
  "tarot guia completo",
  "curso de numerologia",
  "apostila de inglês",
  "curso de espanhol online",
  "guia de caligrafia artística",
  "curso de desenho realista",
  "moldes de bordado",

  // Segunda leva — nichos grandes do mercado brasileiro de baixo ticket que
  // ainda não estavam cobertos (maternidade, casamento, datas sazonais,
  // creator economy, finanças pessoais, journaling, neurodivergência,
  // ofícios adicionais).
  "chá de bebê digital",
  "diário da gestante",
  "kit mesversário digital",
  "planner de gravidez",
  "álbum do bebê para imprimir",
  "kit chá revelação digital",
  "planner de casamento editável",
  "convites de casamento digital",
  "kit noiva digital",
  "lista de convidados editável",
  "livro de assinaturas para imprimir",
  "moldes de natal",
  "moldes de páscoa",
  "moldes de halloween",
  "kit natal digital",
  "kit páscoa digital",
  "decoração junina para imprimir",
  "templates para Canva Instagram",
  "pack de stories editáveis",
  "kit redes sociais digital",
  "moldura para reels editável",
  "planner de conteúdo editável",
  "planilha de controle financeiro",
  "planilha de orçamento doméstico",
  "planner de finanças pessoais",
  "planilha de gastos mensais",
  "bullet journal editável",
  "diário de gratidão para imprimir",
  "planner de metas editável",
  "diário de autoconhecimento",
  "rotina visual autismo",
  "material PECS para imprimir",
  "quadro de rotina infantil",
  "material TDAH para imprimir",
  "curso de barbeiro online",
  "curso de corte masculino",
  "catálogo de tatuagem digital",
  "kit para tatuadores digital",
  "moldes de unha decorada",
  "cardápio digital editável",
  "planner escolar editável",
  "kit professor digital",
];

export function dayOfYear(date: Date = new Date()): number {
  const start = new Date(date.getFullYear(), 0, 0);
  const diff = date.getTime() - start.getTime();
  return Math.floor(diff / 86_400_000);
}

// Retorna as próximas `count` keywords, em rotação circular, a partir do
// índice determinado pelo dia do ano — garante cobertura de todas ao longo
// do tempo sem repetir sempre as mesmas primeiras da lista.
export function keywordsForToday(count = 7, date: Date = new Date()): string[] {
  const start = dayOfYear(date) % KEYWORDS.length;
  const result: string[] = [];
  for (let i = 0; i < count; i++) {
    result.push(KEYWORDS[(start + i) % KEYWORDS.length]);
  }
  return result;
}
